---
resource_name: "vpc"

context:
  env_name: "Example"
  region: "ap-northeast-2"
  region_name: "apne2"
  project_name: "TF-MODULE"

vpc:
  create: true
  id: null
  info: 
    cidr: "10.240.0.0/16"
    dns_hostnames: true
    dns_support: true
  igw:
    create: true
    id: null
